#!/bin/bash

# packages
_FIREFOX=true
_QUTEBROWSER=true
_DUNST=true
_NEOVIM=true
_KAKOUNE=false

# exit when any command fails
set -e

# config locations
firefox_dir="/home/gurjal/.mozilla/firefox/33zou0x2.default-release"
qutebrowser_dir="$HOME/.config/qutebrowser/"
dunst_dir="$HOME/.config/dunst/"
theme=''

usage() {
    echo 'usage: set_theme [theme] [flags]'
    echo
    echo '  no args           use menu to set theme and background'
    echo '  -h, --help        u a dum'
}

set_theme_bg() {
    _set_bg_command="set-bg -r0 -f"
    case "$1" in
        1  | catppuccin)
            $_set_bg_command "/home/$USER/Pictures/wallpapers/4k/blueorange_temple_5120x2160.png"
            theme='catppuccin'
            ;;
        2  | ayu)
            $_set_bg_command "/home/$USER/Pictures/wallpapers/4k/267592.jpeg"
            theme='ayu'
            ;;
        3  | palenight)
            $_set_bg_command "/home/$USER/Pictures/wallpapers/4k/outset_island_night.jpg"
            # set-bg -r0 -f "/home/$USER/Pictures/wallpapers/4k/833406.jpg"
            theme='palenight'
            ;;
        4  | everforest)
            # set-bg -r0 -b "/home/$USER/Pictures/wallpapers/4k/island_trees.jpeg"
            $_set_bg_command "/home/$USER/Pictures/wallpapers/4k/IMG_20210318_132240.jpg"
            theme='everforest'
            ;;
        5  | rose-pine)
            $_set_bg_command "/home/$USER/Pictures/wallpapers/4k/purple_peach_mountain_sunset.jpg"
            theme='rose-pine'
            ;;
        6  | gruvbox)
            $_set_bg_command "/home/$USER/Pictures/wallpapers/windows/letter-by-bangjoy1992-4096-x-2081-v0-6zsqbsxu5nka1.jpg"
            theme='gruvbox'
            ;;
        7  | embark)
            # set-bg -r0 -b "/home/$USER/Pictures/wallpapers/3k/694956.jpg"
            # set-bg -r0 -b "/home/$USER/Pictures/wallpapers/windows/view-of-the-parade-of-planets-2560x1440-v0-uwax6cf8ojma1.png"
            $_set_bg_command "/home/$USER/Pictures/wallpapers/4k/1044012.jpg"
            theme='embark'
            ;;
        8  | tokyonight)
            $_set_bg_command "/home/$USER/Pictures/wallpapers/4k/1128360.jpg"
            theme='tokyonight'
            ;;
        9  | nord)
            $_set_bg_command "/home/$USER/Pictures/wallpapers/Colorthemes/Nord/Nordic6_cropped.jpg"
            theme='nord'
            ;;
        10  | moonfly)
            $_set_bg_command "/home/$USER/Pictures/wallpapers/4k/870592.jpeg"
            theme='moonfly'
            ;;
        11 | seoul256)
            $_set_bg_command "/home/$USER/Pictures/wallpapers/windows/letter-by-bangjoy1992-4096-x-2081-v0-6zsqbsxu5nka1.jpg"
            theme='seoul256'
            ;;
        12 | tundra)
            $_set_bg_command "/home/$USER/Pictures/wallpapers/4k/0oui0mtf451a1.jpg"
            theme='tundra'
            ;;
    esac
}

if [ -z "$1" ]; then
    echo "1  -> catppuccin"
    echo "2  -> ayu"
    echo "3  -> palenight"
    echo "4  -> everforest"
    echo "5  -> rose-pine"
    echo "6  -> gruvbox"
    echo "7  -> embark"
    echo "8  -> tokyonight"
    echo "9  -> nord"
    echo "10 -> moonfly"
    echo "11 -> seoul256"
    echo "12 -> tundra"
    read -p "which theme? " opt
    set_theme_bg $opt
else
    while [ -n "$1" ]; do
        case "$1" in
            -h | --help)
                usage
                exit
                ;;
            *)
                theme=$1
                ;;
        esac
        shift
    done
fi

# keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
# echo an error message before exiting
trap 'echo "\"${last_command}\" command filed with exit code $?."' EXIT

if $_FIREFOX; then
    # [[ -x /usr/bin/pkill ]] && pkill firefox
    # [[ -x /usr/bin/killall ]] && killall firefox

    # set firefox css
    cp ".config/firefox/userChrome.css" "$firefox_dir/chrome"
    cp ".config/themes/$theme/firefox/userColors.css" "$firefox_dir/chrome"

    # set blank page color
    normal_bg=$(cat ".config/themes/$theme/firefox/userColors.css" | grep 'normal_bg' |
        awk '{print $2}' | cut -b -7)
    sed -i '/browser.display.background_color.dark/d' "$firefox_dir/prefs.js"
    echo "user_pref(\"browser.display.background_color.dark\", \"$normal_bg\");" >>"$firefox_dir/prefs.js"
fi

if $_QUTEBROWSER; then
    # qutebrowser theme
    # sed -i '/config.source/d' "$HOME/.config/qutebrowser/config.py"
    # echo "config.source('themes/$theme.py')" >> "$HOME/.config/qutebrowser/config.py"
    cp ".config/themes/$theme/qutebrowser/qtbtheme.py" "$qutebrowser_dir"
fi

if $_DUNST; then
    # set dunst color
    cp ".config/dunst/dunstrc" "$dunst_dir/"
    cat ".config/themes/$theme/dunst/dunstrc_color" >>"$dunst_dir/dunstrc"
fi

if $_NEOVIM; then
    # neovim theme
    sed -i "s+vim.cmd.colorscheme(\".*+vim.cmd.colorscheme(\"$theme\")+g"  $HOME/.config/nvim/init.lua
fi

if $_KAKOUNE; then
    # kakoune theme
    sed -i "/colorscheme/c\colorscheme $theme" "$HOME/.config/kak/kakrc"
fi

# set st and dwm themes then compile
sed -i "s+themes/.*+themes/$theme.h\"+g" tabbed/config.h
sed -i "s+themes/.*+themes/$theme.h\"+g" st/config.h
sed -i "s+themes/.*+themes/$theme.h\"+g" dwm/config.h
cd tabbed
sudo make clean install
cd ../st
sudo make clean install
cd ../dwm
sudo make clean install
cd ..
# [[ -x /usr/bin/pkill ]] && pkill dwm
# [[ -x /usr/bin/killall ]] && killall dwm
echo
echo 'restart dwm'
echo
