#!/bin/bash

# exit when any command fails
set -e

usage() {
    echo 'usage: set_theme [theme] [flags]'
    echo
    echo '  no args           use menu to set theme and background'
    echo '  --no-bg           dont set default background for theme'
    echo '  -a, --alpha       set alpha value to float supplied'
    echo '  -h, --help        u a dum'
}

firefox_dir="/home/gurjal/.mozilla/firefox/2x0rjosj.default-esr"
dunst_dir="$HOME/.config/dunst"
theme=''

set_theme_bg() {
    case "$1" in
        1  | catppuccin)
            set-bg -r0 -b "/home/$USER/Pictures/wallpapers/4k/blueorange_temple_5120x2160.png"
            theme='catppuccin'
            ;;
        2  | ayu)
            set-bg -r0 -b "/home/$USER/Pictures/wallpapers/4k/267592.jpeg"
            theme='ayu'
            ;;
        3  | palenight)
            set-bg -r0 -b "/home/$USER/Pictures/wallpapers/4k/outset_island_night.jpg"
            theme='palenight'
            ;;
        4  | everforest)
            set-bg -r0 -b "/home/$USER/Pictures/wallpapers/4k/island_trees.jpeg"
            theme='everforest'
            ;;
        5  | rose-pine)
            set-bg -r0 -b "/home/$USER/Pictures/wallpapers/4k/purple_peach_mountain_sunset.jpg"
            theme='rose-pine'
            ;;
        6  | gruvbox)
            set-bg -r0 -b "/home/$USER/Pictures/wallpapers/windows/letter-by-bangjoy1992-4096-x-2081-v0-6zsqbsxu5nka1.jpg"
            theme='gruvbox'
            ;;
        7  | embark)
            # set-bg -r0 -b "/home/$USER/Pictures/wallpapers/3k/694956.jpg"
            set-bg -r0 -b "/home/$USER/Pictures/wallpapers/windows/view-of-the-parade-of-planets-2560x1440-v0-uwax6cf8ojma1.png"
            theme='embark'
            ;;
        8  | tokyonight)
            set-bg -r0 -b "/home/$USER/Pictures/wallpapers/4k/1128360.jpg"
            theme='tokyonight'
            ;;
        9  | nord)
            set-bg -r0 -b "/home/$USER/Pictures/wallpapers/Colorthemes/Nord/Nordic6_cropped.jpg"
            theme='nord'
            ;;
        10  | moonfly)
            set-bg -r0 -b "/home/$USER/Pictures/wallpapers/4k/870592.jpeg"
            theme='moonfly'
            ;;
        11 | seoul256)
            set-bg -r0 -b "/home/$USER/Pictures/wallpapers/4k/outset_island_night.jpg"
            theme='seoul256'
            ;;
        12 | tundra)
            set-bg -r0 -b "/home/$USER/Pictures/wallpapers/4k/0oui0mtf451a1.jpg"
            theme='tundra'
            ;;
    esac
}

if [ -z "$1" ]; then
    echo "1  -> catppuccin"
    echo "2  -> ayu"
    echo "3  -> palenight"
    echo "4  -> everforest"
    echo "5  -> rose-pine"
    echo "6  -> gruvbox"
    echo "7  -> embark"
    echo "8  -> tokyonight"
    echo "9  -> nord"
    echo "10 -> moonfly"
    echo "11 -> seoul256"
    echo "12 -> tundra"
    read -p "which theme? " opt
    set_theme_bg $opt
else
    while [ -n "$1" ]; do
        case "$1" in
            -h | --help)
                usage
                exit
                ;;
            --no-bg)
                no_bg=1
                ;;
            *)
                theme=$1
                ;;
        esac
        shift
    done
fi

# keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
# echo an error message before exiting
trap 'echo "\"${last_command}\" command filed with exit code $?."' EXIT

# set background if needed
if [ -z "$no_bg" ]; then
    set_theme_bg $theme
fi

# [[ -x /usr/bin/pkill ]] && pkill firefox
# [[ -x /usr/bin/killall ]] && killall firefox

# set dunst color
cp ".config/dunst/dunstrc" "$dunst_dir/"
cat ".config/themes/$theme/dunst/dunstrc_color" >>"$dunst_dir/dunstrc"

# set firefox css
cp ".config/firefox/userChrome.css" "$firefox_dir/chrome"
cp ".config/themes/$theme/firefox/userColors.css" "$firefox_dir/chrome"

# set blank page color
normal_bg=$(cat ".config/themes/$theme/firefox/userColors.css" | grep 'normal_bg' |
    awk '{print $2}' | cut -b -7)
sed -i '/browser.display.background_color.dark/d' "$firefox_dir/prefs.js"
echo "user_pref(\"browser.display.background_color.dark\", \"$normal_bg\");" >>"$firefox_dir/prefs.js"

# qutebrowser
sed -i '/config.source/d' "$HOME/.config/qutebrowser/config.py"
echo "config.source('themes/$theme.py')" >> "$HOME/.config/qutebrowser/config.py"

# neovim
sed -i "s+vim.cmd.colorscheme(\".*+vim.cmd.colorscheme(\"$theme\")+g"  $HOME/.config/nvim/init.lua

# kakoune
# sed -i "/colorscheme/c\colorscheme $theme" "$HOME/.config/kak/kakrc"

# set st and dwm themes then compile
sed -i "s+themes/.*+themes/$theme.h\"+g" tabbed/config.h
sed -i "s+themes/.*+themes/$theme.h\"+g" st/config.h
sed -i "s+themes/.*+themes/$theme.h\"+g" dwm/config.h
cd tabbed
sudo make clean install
cd ../st
sudo make clean install
cd ../dwm
sudo make clean install
cd ..
# [[ -x /usr/bin/pkill ]] && pkill dwm
# [[ -x /usr/bin/killall ]] && killall dwm
echo
echo 'restart dwm'
echo
